project/onboarding/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.logi, name='login'),
    path('logout/', views.logo, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create/candidate/', views.create_candidate, name='create_candidate'),
    path('edit/candidate/<int:cid>/', views.update_candidate, name='edit_candidate'),
    path('view/candidate/<int:cid>/', views.view_candidate, name='view_candidate'),
    path('all/candidate/', views.all_candidate, name='all_candidate'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('onboarding.urls', 'onboarding'), namespace="onboarding")),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/onboarding/models.py
from django.db import models
from django.contrib.auth.models import User, Group

class function(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class sub_function(models.Model):
    id = models.AutoField(primary_key=True)
    fk_function = models.ForeignKey(function, on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name

class designation(models.Model):
    id = models.AutoField(primary_key=True)
    fk_function = models.ForeignKey(function, on_delete=models.CASCADE, null=True, default=None)
    fk_sub_function = models.ForeignKey(sub_function, on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name

class state(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300)
    NORTH = 'N'
    EAST = 'E'
    WEST = 'W'
    SOUTH = 'S'
    REGION_CHOICES = [
        (NORTH, 'North'),
        (EAST, 'East'),
        (WEST, 'West'),
        (SOUTH, 'South'),
    ]
    region = models.CharField(max_length=10, choices=REGION_CHOICES, default=None, null=True)
    def __str__(self):
        return self.name

class location(models.Model):
    id = models.AutoField(primary_key=True)
    fk_state = models.ForeignKey(state, on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name

class sub_location(models.Model):
    id = models.AutoField(primary_key=True)
    fk_state = models.ForeignKey(state, on_delete=models.CASCADE, null=True, default=None)
    fk_location = models.ForeignKey(location, on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name
        
class user_group(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey( User, on_delete=models.CASCADE, null=True, default=None, blank=True)
    group = models.ForeignKey( Group, on_delete=models.CASCADE, null=True, default=None, blank=True)
    first_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=10)
    adhaar = models.CharField(max_length=12)
    def __str__(self):
        return self.first_name + '|' + str(self.group.name)

class candidate(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=10)
    adhaar = models.CharField(max_length=12)
    doj = models.DateField(null=True, blank=True, default=None)
    fk_function = models.ForeignKey(function, on_delete=models.CASCADE, null=True, default=None)
    fk_sub_function = models.ForeignKey(sub_function, on_delete=models.CASCADE, null=True, default=None)
    fk_designation = models.ForeignKey(designation, on_delete=models.CASCADE, null=True, default=None)
    fk_state = models.ForeignKey(state, on_delete=models.CASCADE, null=True, default=None)
    fk_location = models.ForeignKey(location, on_delete=models.CASCADE, null=True, default=None)
    fk_sub_location = models.ForeignKey(sub_location, on_delete=models.CASCADE, null=True, default=None)
    created_by = models.CharField(max_length=100)
    created_datetime = models.DateTimeField(auto_now_add=True)
    recruiter = models.CharField(max_length=100, default='R001')
    obspoc = models.ForeignKey( user_group, on_delete=models.CASCADE, null=True, default=None)
    status = models.CharField(max_length=100)
    group = models.ForeignKey( Group, on_delete=models.CASCADE, null=True, default=4, blank=True)

    def __str__(self):
        return self.first_name + ' ' + str(self.last_name)

project/onboarding/views.py
from . import models
from django.shortcuts import redirect, render
from .constants import *
from django.contrib.auth import authenticate, login, logout

def logo(request):
    logout(request)
    return redirect('onboarding:login')

def logi(request):
    if request.method == 'POST':
        username = request.POST.get('username').title()
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('onboarding:dashboard')
        else:
            print("Invalid Credentials")
            return render(request, LOGIN_HTML, {'err': 'Invalid Credentials'})
    return render(request, LOGIN_HTML)

def dashboard(request):
    group = getattr(models, 'user_group').objects.filter(**{'user__username': str(request.user)}).values_list('group__name', flat=True)[0]
    if group == 'Recruiter':
        pending = getattr( models, 'candidate').objects.filter(**{'created_by': str(request.user), 'status': 'Pending'}).order_by('created_datetime').count()
        approved = getattr( models, 'candidate').objects.filter(**{'created_by': str(request.user), 'status': 'Approved'}).order_by('created_datetime').count()
    elif group == 'Obspoc':
        pending = getattr( models, 'candidate').objects.filter(**{'obspoc': str(request.user), 'status': 'Pending'}).order_by('created_datetime').count()
        approved = getattr( models, 'candidate').objects.filter(**{'obspoc': str(request.user), 'status': 'Approved'}).order_by('created_datetime').count()
    else:
        pending = getattr( models, 'candidate').objects.filter(**{'status': 'Pending'}).order_by('created_datetime').count()
        approved = getattr( models, 'candidate').objects.filter(**{'status': 'Approved'}).order_by('created_datetime').count()

    return render(request, DASHBOARD_CONTAINER_HTML, {'group': group, 'pending': pending, 'approved': approved})

def create_candidate(request):
    if request.method == 'POST':
        save_map = {
            'first_name': request.POST.get('firstname'),
            'middle_name': request.POST.get('middlename'),
            'last_name':request.POST.get('lastname'),
            'dob':request.POST.get('dob'),
            'phone':request.POST.get('phone'),
            'adhaar':request.POST.get('adhaar'),
            'doj':None,
            'fk_function_id':int(request.POST.get('function')),
            'fk_sub_function_id':int(request.POST.get('subfunction')),
            'fk_designation_id':int(request.POST.get('designation')),
            'fk_state_id':int(request.POST.get('state')),
            'fk_location_id':int(request.POST.get('location')),
            'fk_sub_location_id':int(request.POST.get('sublocation')),
            'created_by':str(request.user),
            'recruiter':str(request.user),
            'obspoc_id':int(request.POST.get('obspoc')),
            'status':'Pending'
        }
        print(save_map)
        a = getattr(models, 'candidate').objects.create(**save_map)
        
        print('Candidate created successfully')
        group = getattr(models, 'user_group').objects.filter(**{'user__username': str(request.user)}).values_list('group__name', flat=True)[0]
        if group == 'Recruiter':
            all_candidate = getattr( models, 'candidate').objects.filter(**{'created_by': str(request.user)}).order_by('created_datetime')
        else:
            all_candidate = getattr( models, 'candidate').objects.all().order_by('created_datetime')
        return render(request, CANDIDATE_TABLE_CONTAINER_HTML, {'data': all_candidate})
    context = {
        'function' : getattr(models, 'function').objects.all(),
        'subfunction' : getattr(models, 'sub_function').objects.all(),
        'designation' : getattr(models, 'designation').objects.all(),
        'state' : getattr(models, 'state').objects.all(),
        'location' : getattr(models, 'location').objects.all(),
        'sublocation' : getattr(models, 'sub_location').objects.all(),
        'recruiters': getattr(models, 'user_group').objects.filter(**{'group__name': 'Recruiter'}),
        'obspocs': getattr(models, 'user_group').objects.filter(**{'group__name': 'Obspoc'})
    }
    return render(request, CANDIDATE_CRUD_CONTAINER_HTML, context)

def update_candidate(request, cid):
    if request.method == 'POST':
        save_map = {
            'status':'Pending'
        }
        getattr(models, 'candidate').objects.filter(**{'pk': cid}).update(**save_map)
        msg = 'Candidate updated successfully'
        all_candidate = getattr( models, 'candidate').objects.filter(**{'created_by': str(request.user)}).order_by('created_datetime')
        return render(request, CANDIDATE_TABLE_CONTAINER_HTML, {'data': all_candidate})
    selected = getattr(models, 'candidate').objects.get(**{'id': cid})
    return render(request, CANDIDATE_EDIT_CONTAINER_HTML, {'selected': selected})

def view_candidate(request, cid):    
    selected = getattr(models, 'candidate').objects.get(**{'id': cid})
    return render(request, CANDIDATE_VIEW_CONTAINER_HTML, {'selected': selected})

def all_candidate(request):
    group = getattr(models, 'user_group').objects.filter(**{'user__username': str(request.user)}).values_list('group__name', flat=True)[0]
    if group == 'Recruiter':
        all_candidate = getattr( models, 'candidate').objects.filter(**{'created_by': str(request.user)}).order_by('created_datetime')
    elif group == 'Obspoc':
        all_candidate = getattr( models, 'candidate').objects.filter(**{'obspoc': str(request.user)}).order_by('created_datetime')
    else:
        all_candidate = getattr( models, 'candidate').objects.all().order_by('created_datetime')
    return render(request, CANDIDATE_TABLE_CONTAINER_HTML, {'data': all_candidate})

project/onboarding/templates/candidate/crud/container.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include 'utilities/head.html' with title='Onboarding - Create Candidate!' css_link='onboarding/css/dashboard.css' css_link2='onboarding/css/form.css' %}
  </head>  
  <body>
    <!-- navbar start -->
    {% include 'utilities/navbar.html' %}
    <!-- navbar end -->

    <!-- form -->
    {% include 'candidate/crud/form.html' %}
    <!-- form end -->
  </body>
</html>

project/onboarding/templates/candidate/crud/edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include 'utilities/head.html' with title='Onboarding - Update Candidate!' css_link='onboarding/css/dashboard.css' css_link2='onboarding/css/form.css' %}
  </head>  
  <body>
    <!-- navbar start -->
    {% include 'utilities/navbar.html' %}
    <!-- navbar end -->
    <div class="form_container">
        <div class="form_header">
            <h3>Candidate Status Update Form</h3>
        </div>
        <form action="">
            <div class="input__row">
                <div class="input__div">
                    <input class="form__input" disabled type="text" name="firstname" id="firstname" maxlength="50"
                        placeholder=" " autofocus tabindex="1" required value="{{ selected.firstname }}">
                    <label for="firstname" class="form__label">First Name</label>
                </div>
                <div class="input__div">
                    <input class="form__input" value="{{ selected.middlename }}" disabled type="text" name="middlename" id="middlename" maxlength="10"
                        placeholder=" "  tabindex="2" required>
                    <label for="middlename" class="form__label">Middle Name</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <input class="form__input" value="{{ selected.lastname }}" disabled type="text" name="lastname" id="lastname" maxlength="10"
                        placeholder=" "  tabindex="3" required>
                    <label for="lastname" class="form__label">Last Name</label>
                </div>
                <div class="input__div">
                    <input class="form__input" disabled type="date" name="dob" id="dob"
                        placeholder=" " value="{{ selected.dob }}" tabindex="4" required>
                    <label for="dob" class="form__label">Date of Birth</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <input class="form__input" disabled type="text" name="phone" id="phone" maxlength="10"
                        placeholder=" "  tabindex="5" value="{{ selected.phone }}" required>
                    <label for="phone" class="form__label">Phone</label>
                </div>
                <div class="input__div">
                    <input class="form__input" disabled type="text" name="adhaar" id="adhaar" maxlength="12"
                        placeholder=" "  tabindex="6" value="{{ selected.adhaar }}" required>
                    <label for="adhaar" class="form__label">Adhaar</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <input class="form__input" disabled type="date" name="doj" id="doj"
                        placeholder=" " tabindex="7" value="{{ selected.doj }}" required>
                    <label for="doj" class="form__label">Date of Joining</label>
                </div>
                <div class="input__div">
                    <select class="form__input" disabled tabindex="8"  required name="function" id="function">
                        <option value="{{ selected.fk_function_id }}" selected>{{ selected.fk_function }}</option>
                        {% for each in function %}
                            <option value="{{ each.pk }}" id="{{ each.pk }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="function" class="form__label">Function</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <select class="form__input" disabled tabindex="9" required name="subfunction" id="subfunction">
                        <option value="{{ selected.fk_sub_function_id }}" selected>{{ selected.fk_sub_function }}</option>

                        {% for each in subfunction %}
                            <option value="{{ each.pk }}" id="{{ each.fk_function_id }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="subfunction" class="form__label">Sub Function</label>
                </div>
                <div class="input__div">
                    <select class="form__input" disabled tabindex="10" required name="designation" id="designation">
                        <option value="{{ selected.fk_designation_id }}" selected>{{ selected.fk_designation }}</option>

                        {% for each in designation %}
                            <option value="{{ each.pk }}" id="{{ each.fk_sub_function_id }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="designation" class="form__label">Designation</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <select class="form__input" disabled tabindex="11" required name="state" id="state">
                        <option value="{{ selected.fk_state_id }}" selected>{{ selected.fk_state }}</option>

                        {% for each in state %}
                            <option value="{{ each.pk }}" id="{{ each.pk }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="state" class="form__label">State</label>
                </div>
                <div class="input__div">
                    <select class="form__input" disabled tabindex="12" required name="location" id="location">
                        <option value="{{ selected.fk_location_id }}" selected>{{ selected.fk_location }}</option>

                        {% for each in location %}
                            <option value="{{ each.pk }}" id="{{ each.fk_location_id }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="location" class="form__label">Location</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <select class="form__input" disabled tabindex="13" required name="sublocation" id="sublocation">
                        <option value="{{ selected.fk_sub_location_id }}" selected>{{ selected.fk_sub_location }}</option>

                        {% for each in sublocation %}
                            <option value="{{ each.pk }}" id="{{ each.fk_location_id }}">{{ each.name }}</option>
                        {% endfor %}
                    </select>
                    <label for="sublocation" class="form__label">Sub Location</label>
                </div>
                <div class="input__div">
                    <select class="form__input" disabled tabindex="14" required name="recuiter" id="recuiter">
                        <option value="{{ selected.recruiter }}" selected>{{ selected.recruiter }}</option>

                        {% for each in recruiters %}
                            <option value="{{ each.user_id }}">{{ each.user_id }} | {{ each.first_name }} {{ each.last_name }}</option>
                        {% endfor %}
                    </select>
                    <label for="recuiter" class="form__label">Recruiter</label>
                </div>
            </div>
            <div class="input__row">
                <div class="input__div">
                    <select class="form__input" disabled tabindex="15" required name="obspoc" id="obspoc">
                        <option value="{{ selected.obspoc }}" selected>{{ selected.obspoc }}</option>

                        {% for each in obspocs %}
                            <option value="{{ each.user_id }}">{{ each.user_id }} | {{ each.first_name }} {{ each.last_name }}</option>
                        {% endfor %}
                    </select>
                    <label for="obspoc" class="form__label">Onboarding SPOC</label>
                </div>
                <div class="input__div">
                    <select id="status" tabindex="16" name="status" class="form__input">
                        <option value="{{ selected.status }}" selected>{{ selected.status }}</option>
                        <option value="Pending">Pending</option>
                        <option value="Approve">Approve</option>
                        <option value="Reject">Reject</option>
                    </select>
                    <label for="status" class="form__label">Status</label>
                </div>
            </div>
            <div class="save_btn_div">
                <button type="submit" class="save_btn">Submit</button>
                <button type="button" class="cancel_btn">Cancel</button>
            </div>
        </form>
    </div>
</body>
</html>

project/onboarding/templates/candidate/crud/form.html
<div class="form_container">
    <div class="form_header">
        <h3>Candidate Creation Form</h3>
    </div>
    <form action="{% url 'onboarding:create_candidate' %}" method="post">
        {% csrf_token %}
        <div class="input__row">
            <div class="input__div">
                <input class="form__input" type="text" name="firstname" id="firstname" maxlength="50"
                       placeholder=" " autofocus tabindex="1" required>
                <label for="firstname" class="form__label">First Name</label>
            </div>
            <div class="input__div">
                <input class="form__input" type="text" name="middlename" id="middlename" maxlength="10"
                       placeholder=" "  tabindex="2">
                <label for="middlename" class="form__label">Middle Name</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <input class="form__input" type="text" name="lastname" id="lastname" maxlength="10"
                       placeholder=" "  tabindex="3">
                <label for="lastname" class="form__label">Last Name</label>
            </div>
            <div class="input__div">
                <input class="form__input" type="date" name="dob" id="dob"
                       placeholder=" " tabindex="4" required>
                <label for="dob" class="form__label">Date of Birth</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <input class="form__input" type="text" name="phone" id="phone" maxlength="10"
                       placeholder=" " pattern="^[6-9]{1}[0-9]{9}$"  tabindex="5" required>
                <label for="phone" class="form__label">Phone</label>
            </div>
            <div class="input__div">
                <input class="form__input" type="text" name="adhaar" id="adhaar" maxlength="12"
                       placeholder=" "  tabindex="6" pattern="^[0-9]{12}$" required>
                <label for="adhaar" class="form__label">Adhaar</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <input class="form__input" type="date" name="doj" id="doj"
                       placeholder=" " tabindex="7" disabled>
                <label for="doj" class="form__label">Date of Joining</label>
            </div>
            <div class="input__div">
                <select class="form__input" tabindex="8" required name="function" id="function">
                    <option value=""></option>
                    {% for each in function %}
                        <option value="{{ each.pk }}" id="{{ each.pk }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="function" class="form__label">Function</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <select class="form__input" tabindex="9" required name="subfunction" id="subfunction">
                    <option value=""></option>
                    {% for each in subfunction %}
                        <option value="{{ each.pk }}" id="{{ each.fk_function_id }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="subfunction" class="form__label">Sub Function</label>
            </div>
            <div class="input__div">
                <select class="form__input" tabindex="10" required name="designation" id="designation">
                    <option value=""></option>
                    {% for each in designation %}
                        <option value="{{ each.pk }}" id="{{ each.fk_sub_function_id }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="designation" class="form__label">Designation</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <select class="form__input" tabindex="11" required name="state" id="state">
                    <option value=""></option>
                    {% for each in state %}
                        <option value="{{ each.pk }}" id="{{ each.pk }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="state" class="form__label">State</label>
            </div>
            <div class="input__div">
                <select class="form__input" tabindex="12" required name="location" id="location">
                    <option value=""></option>
                    {% for each in location %}
                        <option value="{{ each.pk }}" id="{{ each.fk_location_id }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="location" class="form__label">Location</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <select class="form__input" tabindex="13" required name="sublocation" id="sublocation">
                    <option value=""></option>
                    {% for each in sublocation %}
                        <option value="{{ each.pk }}" id="{{ each.fk_location_id }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
                <label for="sublocation" class="form__label">Sub Location</label>
            </div>
            <div class="input__div">
                <select class="form__input" tabindex="14" required name="recuiter" id="recuiter">
                    <option value=""></option>
                    {% for each in recruiters %}
                        <option value="{{ each.user_id }}">{{ each.user_id }} | {{ each.first_name }} {{ each.last_name }}</option>
                    {% endfor %}
                </select>
                <label for="recuiter" class="form__label">Recruiter</label>
            </div>
        </div>
        <div class="input__row">
            <div class="input__div">
                <select class="form__input" tabindex="15" required name="obspoc" id="obspoc">
                    <option value=""></option>
                    {% for each in obspocs %}
                        <option value="{{ each.user_id }}">{{ each.user_id }} | {{ each.first_name }} {{ each.last_name }}</option>
                    {% endfor %}
                </select>
                <label for="obspoc" class="form__label">Onboarding SPOC</label>
            </div>
            <div class="input__div">
                <input type="text" id="status" tabindex="16" name="status" readonly value="Pending" class="form__input" placeholder=" ">
                <label for="status" class="form__label">Status</label>
            </div>
        </div>
        <div class="save_btn_div">
            <button type="submit" class="save_btn">Submit Candidate</button>
            <button type="button" class="cancel_btn">Cancel</button>
        </div>
    </form>
</div>